FROM maven:3.9.9-eclipse-temurin-21 AS dev

WORKDIR /app

# Copy parent POM first
COPY pom.xml ./pom.xml

# Install parent POM to local repository
RUN mvn -q -B -N install

# Copy commons-shared (includes proto & avro)
COPY commons-shared/pom.xml ./commons-shared/pom.xml
COPY ./commons-shared/src ./commons-shared/src

# Build and install commons-shared
WORKDIR /app/commons-shared
RUN mvn -q -B -DskipTests clean install

# Copy notification-service POM ONLY
COPY notification-service/pom.xml /app/notification-service/pom.xml

# Resolve dependencies
WORKDIR /app/notification-service
# RUN mvn -q -B -DskipTests dependency:go-offline

EXPOSE 8080 9090 5005

ENTRYPOINT sh -c "mvn clean install -U -DskipTests && mvn spring-boot:run -Dspring-boot.run.fork=false -Dspring-boot.run.jvmArguments='-javaagent:/otel-agent.jar -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"
