services:
  delivery-service:
    build:
      context: ..
      dockerfile: ./delivery-service/Dockerfile.dev
    container_name: delivery-service
    ports:
      - "9003:8080" # Expose application port
      - "5003:5005" # Expose debug port
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_KAFKA_CONSUMER_GROUP_ID: delivery-consumer-group
      GRPC_CLIENT_TENANT_SERVICE_ADDRESS: static://tenant-service:9090
      OTEL_SERVICE_NAME: delivery-service
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev

    # ===== WATCH MODE CONFIGURATION =====
    develop:
      watch:
        - action: sync+restart
          path: ../delivery-service/src
          target: /app/delivery-service/src
          ignore:
            - node_modules
            - target
        - action: rebuild
          path: ../delivery-service/pom.xml

    # ===== VOLUME MOUNTS =====
    volumes:
      - ~/.m2:/root/.m2
      - ../delivery-service/src:/app/delivery-service/src
      - ../delivery-service/pom.xml:/app/delivery-service/pom.xml
      - ../agents/opentelemetry-javaagent.jar:/otel-agent.jar:ro

    networks:
      - notification-net

networks:
  notification-net:
    external: true